apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-egressip-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-egressip-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aws-egressip-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "aws-egressip-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aws-egressip-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - aws-egressip-operator
          env:
            - name: CLUSTER_NAME
              value: {{ required "Please provide the name of the cluster as .Values.clusterName !" .Values.clusterName }}
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ include "aws-egressip-operator.fullname" . }}
            - name: AWS_REGION
              value: {{ .Values.awsRegion }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: 8080-tcp
              containerPort: 8080
              protocol: TCP
            - name: 8383-tcp
              containerPort: 8383
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}