{{- if .Values.alert.create }}
kind: ClusterRoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: monitor-{{ include "aws-egressip-operator.fullname" . }}
roleRef:
  kind: ClusterRole
  name: monitor-{{ include "aws-egressip-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
groupNames: []
userNames:
  - system:serviceaccount:openshift-monitoring:prometheus-k8s
{{- end }}