kind: Service
apiVersion: v1
metadata:
  name: {{ include "aws-egressip-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-egressip-operator.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ include "aws-egressip-operator.fullname" . }}
    app.kubernetes.io/name: {{ include "aws-egressip-operator.fullname" . }}
  ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081





