{{- if .Values.alert.create }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              openshift.io/cluster-monitoring: "true"
      ports:
        - port: 8081
          protocol: TCP
  podSelector:
    matchLabels:
      monitored: "true"
  policyTypes:
    - Ingress
{{- end }}