{{- if .Values.alert.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitor-{{ include "aws-egressip-operator.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
      - namespaces
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - "/metrics"
    verbs: ["get", "list", "watch"]
{{- end }}