{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-egressip-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "aws-egressip-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "aws-egressip-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}